services:
    api:
      build:
        context: ./Docker
        dockerfile: Dockerfile
      image: node-api:1.0.0
      ports:
        - "4000:4000"
      volumes:
        - ./Docker:/app
      environment:
        API_KEY: myapikeyvlaueesdfsdfsdf